### ISSUE TITLE
访问数据库时，经常崩溃，

### ISSUE THREAD

**Issue by YangKai123** [wangzhaomeng/WZMChatUI#2]
/*
 关闭数据库  
 */
-(BOOL)closeDataBase{
    return !sqlite3_close(_sql3);
}
奔溃日志，
[logging] BUG IN CLIENT OF libsqlite3.dylib: illegal multi-threaded access to database connection
求解决方法，谢谢

**Comment by wangzhaomeng** [comment]
你用多个线程去访问数据库了，要屡一下你的代码逻辑，也可以直接把访问数据库相关代码转到主线程

**Comment by YangKai123** [comment]
我全部放到 主线程了，还是 崩溃 报[logging] BUG IN CLIENT OF libsqlite3.dylib: illegal multi-threaded access to database connection
