### ISSUE TITLE
我发现了一个bug

### ISSUE THREAD

**Issue by taozl** [wangzhaomeng/WZMChatUI#6]
先点击这个，
<img width="404" alt="image" src="https://user-images.githubusercontent.com/12944917/124549324-9781eb00-de61-11eb-9987-52ec7af097fa.png">
然后点击
<img width="404" alt="image" src="https://user-images.githubusercontent.com/12944917/124549392-acf71500-de61-11eb-82bc-caba15f4909d.png">
最后就成这样了
<img width="404" alt="image" src="https://user-images.githubusercontent.com/12944917/124549433-bbddc780-de61-11eb-996b-533233235775.png">

**Comment by wangzhaomeng** [comment]
标记
